[build]
functions = "./functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "__sapper__/export"
  exclude=[
      "**/**/subscribed/index.html",
      "**/**/unsubscribed/index.html",
      "**/**/ogImage/index.html"
  ] 