[build]
functions = "./functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

  [plugins.inputs]
  buildDir = "__sapper__/export"
  exclude=[
      "./__sapper__/export/subscribed/index.html",
      "./__sapper__/export/unsubscribed/index.html",
      "./__sapper__/export/ogImage/index.html"
  ] 